// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type Dir struct {
	// Current dir
	Path string `json:"path"`
	// Files in current path
	Files []*File `json:"files"`
	// Subdirs in current path
	Dirs []*Dir `json:"dirs"`
}

type File struct {
	// Unique identifier to the file
	ID string `json:"id"`
	// File name
	Name string `json:"name"`
	// File path
	Path string `json:"path"`
	// File owner
	User int `json:"user"`
	// Content type
	FileType string `json:"fileType"`
	// Size in bytes
	Size int `json:"size"`
	// Creation date
	CreatedAt time.Time `json:"createdAt"`
	// Last update date
	UpdatedAt time.Time `json:"updatedAt"`
	// URL to download the file
	DownloadURL string `json:"downloadURL"`
}

type MoveInput struct {
	// Identifier of the desired file to move
	ID string `json:"id"`
	// Destination user
	User int `json:"user"`
	// Destination path
	NewPath string `json:"newPath"`
}

type UploadInput struct {
	File graphql.Upload `json:"file"`
	// File owner
	User int `json:"user"`
	// Destination path
	Path string `json:"path"`
}
