name: Test, build and deploy image

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Test, build and deploy image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: GolangCI-Lint
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.45.2
          ./bin/golangci-lint run

      - name: Test
        run: |
          go test -race -cover ./...

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          file: build/Dockerfile
          tags: ghcr.io/rafaelrubbioli/fileapi/fileapi:01
